routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




// Admin side routes
Route::group(['as'=>'admin.', 'prefix'=> 'admin', 'middleware' => ['auth']], function(){
    // Category
    Route::resource('category', 'Web\CategoryController');

    // Customer
    Route::resource('customer', 'Web\CustomerController');
    Route::get('/customer/edit/{id}', 'Web\CustomerController@edit')->name('customer.edit');

    // Payment
    Route::resource('payment', 'Web\PaymentController');
    Route::get('/payment/edit/{id}', 'Web\PaymentController@edit')->name('payment.edit');

    // Product
    Route::resource('product', 'Web\ProductController');

    // Supplier
    Route::resource('supplier', 'Web\SupplierController');

    // Shipper
    Route::resource('shipper', 'Web\ShipperController');
    Route::get('/shipper/edit/{id}', 'Web\ShipperController@edit')->name('shipper.edit');

    // variant
    Route::resource('variant', 'Web\VariantController');
    Route::get('/variant/edit/{id}', 'Web\VariantController@edit')->name('variant.edit');

    // Variant Options
    Route::resource('voption', 'Web\VariantOptionController');
    Route::get('voption/create', 'Web\VariantOptionController@create')->name('voption.create');
    Route::get('/voption/edit/{id}', 'Web\VariantOptionController@edit')->name('voption.edit');

    //
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Product;

class Supplier extends Model
{
    use SoftDeletes;

    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'company_name',
        'company_address',
        'company_city',
        'company_phone',
        'company_email',
        'contact_person_name',
        'contact_person_phone',
        'contact_person_email',
        'payment_status',
        'payment_methods',
        'discount',
        'total_amount',
        'type_of_goods',
        'goods_description',
        'created_at',
        'updated_at',
    ];

    public function products(){
        return $this->hasMany(Product::class);
    }

}

app/Http/Controllers/Web/SupplierController.php
<?php

namespace App\Http\Controllers\Web;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Supplier;
use Brian2694\Toastr\Facades\Toastr;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $suppliers = Supplier::latest()->get();
        return view('pages.admin.supplier.index', ['suppliers' => $suppliers]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pages.admin.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'company_name' => 'required | unique:suppliers',
            'company_phone' => 'required',
            'contact_person_name' => 'required',
            'contact_person_phone'=> 'required',

        ],[
            'company_name.required' => 'Company name is required.',
            'company_name.unique' => 'This company name is already exists.',
            'company_phone.required' => 'Company phone number is required',
            'contact_person_name.required' => 'Contact person name is required',
            'contact_person_phone.required' => 'Contact person phone is required'
        ]);

        $data = array(
            'company_name' => $request->input('company_name'),
            'company_address' => $request->input('company_address'),
            'company_city' => $request->input('company_city'),
            'company_phone' => $request->input('company_phone'),
            'company_email' => $request->input('company_email'),
            'contact_person_name' => $request->input('contact_person_name'),
            'contact_person_phone' => $request->input('contact_person_phone'),
            'contact_person_email' => $request->input('contact_person_email'),
            'payment_status' => $request->input('payment_status'),
            'payment_methods' => $request->input('payment_methods'),
            'discount' => $request->input('discount'),
            'total_amount' => $request->input('total_amount'),
            'type_of_goods' => $request->input('type_of_goods'),
            'goods_description' => $request->input('goods_description'),
            'created_at' => date('Y-m-d')
        );

        /*
        echo "<pre>";
        print_r($data);
        die();
        */
        $createResult = Supplier::create($data);

        if($createResult){
            Toastr::success('New supplier info has saved.', 'success');
            return redirect()->route('admin.supplier.index');
        }else{
            Toastr::warning('W00ps! Something went wrong. Try again.', 'warning');
            return redirect()->back();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $supplier = Supplier::findOrFail($id);
        return view('pages.admin.supplier.show', ['supplier' => $supplier]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $supplier = Supplier::findOrFail($id);
        return view('pages.admin.supplier.edit', ['supplier' => $supplier]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'company_name' => 'required | unique:suppliers',
            'company_phone' => 'required',
            'contact_person_name' => 'required',
            'contact_person_phone'=> 'required',

        ],[
            'company_name.required' => 'Company name is required.',
            'company_name.unique' => 'This company name is already exists.',
            'company_phone.required' => 'Company phone number is required',
            'contact_person_name.required' => 'Contact person name is required',
            'contact_person_phone.required' => 'Contact person phone is required'
        ]);

        $data = array(
            'company_name' => $request->input('company_name'),
            'company_address' => $request->input('company_address'),
            'company_city' => $request->input('company_city'),
            'company_phone' => $request->input('company_phone'),
            'company_email' => $request->input('company_email'),
            'contact_person_name' => $request->input('contact_person_name'),
            'contact_person_phone' => $request->input('contact_person_phone'),
            'contact_person_email' => $request->input('contact_person_email'),
            'payment_status' => $request->input('payment_status'),
            'payment_methods' => $request->input('payment_methods'),
            'discount' => $request->input('discount'),
            'total_amount' => $request->input('total_amount'),
            'type_of_goods' => $request->input('type_of_goods'),
            'goods_description' => $request->input('goods_description'),
            'updated_at' => date('Y-m-d')
        );

        $update = Supplier::where('id', $id)->update($data);

        if($update){
            Toastr::success('Supplier info has updated successfully.', 'success');
            return redirect()->route('admin.supplier.show', $id);
        }else{
            Toastr::warning('W00ps! Something went wrong. Try again.', 'warning');
            return redirect()->back();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::findOrFail($id);
        $result = $supplier->delete();

        if($result){
            Toastr::success('Supplier info has deleted.', 'success');
            return redirect()->route('admin.supplier.index');
        }else{
            Toastr::warning('W00ps! Something went wrong. Try again.', 'warning');
            return redirect()->back();
        }
    }
}

resources/views/pages/admin/supplier/create.blade.php
@extends('layouts.admin')
@section('title', 'Supplier')
@push('css')

@endpush
@section('breathcamp')
<ul class="page-breadcrumb">
    <li>
        <i class="fa fa-circle"></i>
        <a href="{{url('/home')}}" >Dashboard</a>
    </li>
    <li class="active">
        <i class="fa fa-circle"></i>
        <a href="{{route('admin.supplier.index')}}">Supplier</a>
    </li>
    <li class="active">
        <i class="fa fa-circle"></i>
        <a href="#">New Supplier</a>
    </li>
</ul>
@endsection

@section('content')
<div class="row">
    <div class="col-md-offset-1 col-md-10">
            <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                             New Supplier </div>
                        <div class="tools">
                            <a href="" class="collapse"> </a>
                            <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                            <a href="" class="reload"> </a>
                            <a href="" class="remove"> </a>
                        </div>
                    </div>
                    <div class="portlet-body form">
                    <form role="form" class="form-horizontal" method="POST" action="{{route('admin.supplier.store')}}">
                        @csrf                          
                        <div class="form-body">
                                <div class="form-group has-success {{ $errors->has('company_name') ? 'has-error' : '' }}">
                                    <label class="col-md-3 control-label">Company Name<span class="text-danger"> * </span></label>
                                    <div class="col-md-9">
                                    <input type="text" name="company_name" value="{{ old('company_name') }}" class="form-control"> 
                                    <span class="text-danger">{{ $errors->first('company_name') }}</span>  
                                    </div>
                                </div>
                                <div class="form-group has-success ">
                                    <label class="col-md-3 control-label">Company Address</label>
                                    <div class="col-md-9">                                        
                                        <input type="text" name="company_address" value="{{ old('company_address') }}" class="form-control">                                         
                                    </div>
                                </div>
                                <div class="form-group has-success">
                                        <label class="col-md-3 control-label">City</label>
                                        <div class="col-md-9">
                                        <input type="text" name="company_city" value="{{ old('company_city') }}" class="form-control"> 
                                        </div>
                                    </div>
                                    <div class="form-group has-success {{ $errors->has('company_phone') ? 'has-error' : '' }}">
                                        <label class="col-md-3 control-label">Company Phone<span class="text-danger"> * </span></label>
                                        <div class="col-md-9">                                            
                                            <input type="text" name="company_phone" value="{{ old('company_phone') }}" class="form-control"> 
                                            <span class="text-danger">{{ $errors->first('company_phone') }}</span>  
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                            <label class="col-md-3 control-label">Company Email</label>
                                            <div class="col-md-9">
                                                <input type="text" name="company_email" value="{{ old('company_email') }}" class="form-control"> 
                                            </div>
                                        </div>
                                        <div class="form-group has-success {{ $errors->has('contact_person_name') ? 'has-error' : '' }}">
                                            <label class="col-md-3 control-label">Contact Person<span class="text-danger"> * </span></label>
                                            <div class="col-md-9">                                                
                                                <input type="text" name="contact_person_name" value="{{ old('contact_person_name') }}" class="form-control"> 
                                                <span class="text-danger">{{ $errors->first('cotact_person_name') }}</span>  
                                            </div>
                                        </div>
                                        <div class="form-group has-success {{ $errors->has('contact_person_phone') ? 'has-error' : '' }}">
                                                <label class="col-md-3 control-label">Contact Person Phone<span class="text-danger"> * </span></label>
                                                <div class="col-md-9">
                                                    <input type="text" name="contact_person_phone" value="{{ old('contact_person_phone') }}" class="form-control"> 
                                                    <span class="text-danger">{{ $errors->first('contact_person_phone') }}</span>  
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Contact Person Email</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="contact_person_email" value="{{ old('contact_person_email') }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Payment Status</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="payment_status" value="{{ old('payment_status') }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Payment Method</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="payment_methods" value="{{ old('payment_methods')}}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Discount (%)</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="discount" value="{{ old('discount') }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Total Amount</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="total_amount" value="{{ old('total_amount') }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                    <label class="col-md-3 control-label">Type of Goods</label>
                                                    <div class="col-md-9">
                                                        <input type="text" name="type_of_goods" value="{{ old('type_of_goods') }}" class="form-control"> 
                                                    </div>
                                                </div>
                                                <div class="form-group has-success">
                                                    <label class="col-md-3 control-label">Goods Short Description</label>
                                                    <div class="col-md-9">
                                                        <input type="text" name="goods_description" value="{{ old('goods_discription') }}" class="form-control"> 
                                                    </div>
                                                </div>
                                
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-4 col-md-8">
                                        <a href="{{route('admin.supplier.index')}}" class="btn default">Cancel</a>
                                        <button type="submit" name="submit" class="btn blue">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
    </div>
</div>
@endsection

@push('js')

@endpush

resources/views/pages/admin/supplier/edit.blade.php
@extends('layouts.admin')
@section('title', 'Supplier')
@push('css')

@endpush
@section('breathcamp')
<ul class="page-breadcrumb">
    <li>
        <i class="fa fa-circle"></i>
        <a href="{{url('/home')}}" >Dashboard</a>
    </li>
    <li class="active">
        <i class="fa fa-circle"></i>
        <a href="{{route('admin.supplier.index')}}">Supplier</a>
    </li>
    <li class="active">
        <i class="fa fa-circle"></i>
        <a href="#">Edit</a>
    </li>
</ul>
@endsection

@section('content')
<div class="row">
    <div class="col-md-offset-1 col-md-10">
            <div class="portlet box blue">
                    <div class="portlet-title">
                        <div class="caption">
                             Supplier info update </div>
                        <div class="tools">
                            <a href="" class="collapse"> </a>
                            <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                            <a href="" class="reload"> </a>
                            <a href="" class="remove"> </a>
                        </div>
                    </div>
                    <div class="portlet-body form">
                    <form role="form" class="form-horizontal" method="POST" action="{{route('admin.supplier.update', $supplier->id)}}">
                        @csrf
                        @method('PATCH')    
                        <div class="form-body">
                                <div class="form-group has-success {{ $errors->has('company_name') ? 'has-error' : '' }}">
                                    <label class="col-md-3 control-label">Company Name</label>
                                    <div class="col-md-9">
                                    <input type="text" name="company_name" value="{{ $supplier->company_name }}" class="form-control"> 
                                    <span class="text-danger">{{ $errors->first('company_name') }}</span>  
                                    </div>
                                </div>
                                <div class="form-group has-success ">
                                    <label class="col-md-3 control-label">Company Address</label>
                                    <div class="col-md-9">                                        
                                        <input type="text" name="company_address" value="{{ $supplier->company_address }}" class="form-control">                                         
                                    </div>
                                </div>
                                <div class="form-group has-success">
                                        <label class="col-md-3 control-label">City</label>
                                        <div class="col-md-9">
                                        <input type="text" name="company_city" value="{{ $supplier->company_city }}" class="form-control"> 
                                        </div>
                                    </div>
                                    <div class="form-group has-success {{ $errors->has('company_phone') ? 'has-error' : '' }}">
                                        <label class="col-md-3 control-label">Company Phone</label>
                                        <div class="col-md-9">                                            
                                            <input type="text" name="company_phone" value="{{ $supplier->company_phone }}" class="form-control"> 
                                            <span class="text-danger">{{ $errors->first('company_phone') }}</span>  
                                        </div>
                                    </div>
                                    <div class="form-group has-success">
                                            <label class="col-md-3 control-label">Company Email</label>
                                            <div class="col-md-9">
                                                <input type="text" name="company_email" value="{{ $supplier->company_email }}" class="form-control"> 
                                            </div>
                                        </div>
                                        <div class="form-group has-success {{ $errors->has('contact_person_name') ? 'has-error' : '' }}">
                                            <label class="col-md-3 control-label">Contact Person</label>
                                            <div class="col-md-9">                                                
                                                <input type="text" name="contact_person_name" value="{{ $supplier->contact_person_name }}" class="form-control"> 
                                                <span class="text-danger">{{ $errors->first('cotact_person_name') }}</span>  
                                            </div>
                                        </div>
                                        <div class="form-group has-success {{ $errors->has('contact_person_phone') ? 'has-error' : '' }}">
                                                <label class="col-md-3 control-label">Contact Person Phone</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="contact_person_phone" value="{{ $supplier->contact_person_phone }}" class="form-control"> 
                                                    <span class="text-danger">{{ $errors->first('contact_person_phone') }}</span>  
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Contact Person Email</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="contact_person_email" value="{{ $supplier->contact_person_email }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Payment Status</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="payment_status" value="{{ $supplier->payment_status }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Payment Method</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="payment_method" value="@if($supplier->payment_methods) {{ $supplier->payment_methods }} @else Unpaid @endif" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Discount (%)</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="discount" value="{{ $supplier->discount }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                <label class="col-md-3 control-label">Total Amount</label>
                                                <div class="col-md-9">
                                                    <input type="text" name="total_amount" value="{{ $supplier->total_amount }}" class="form-control"> 
                                                </div>
                                            </div>
                                            <div class="form-group has-success">
                                                    <label class="col-md-3 control-label">Type of Goods</label>
                                                    <div class="col-md-9">
                                                        <input type="text" name="type_of_goods" value="{{ $supplier->type_of_goods }}" class="form-control"> 
                                                    </div>
                                                </div>
                                                <div class="form-group has-success">
                                                    <label class="col-md-3 control-label">Goods Short Description</label>
                                                    <div class="col-md-9">
                                                        <input type="text" name="goods_description" value="{{ $supplier->goods_description }}" class="form-control"> 
                                                    </div>
                                                </div>
                                
                            </div>
                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-4 col-md-8">
                                        <a href="{{route('admin.supplier.index')}}" class="btn default">Cancel</a>
                                        <button type="submit" name="submit" class="btn blue">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
    </div>
</div>
@endsection

@push('js')

@endpush