routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});




// Admin side routes
Route::group(['as'=>'admin.', 'prefix'=> 'admin', 'middleware' => ['auth']], function(){
    // Category
    Route::resource('category', 'Web\CategoryController');

    // Customer
    Route::resource('customer', 'Web\CustomerController');
    Route::get('/customer/edit/{id}', 'Web\CustomerController@edit')->name('customer.edit');

    // Payment
    Route::resource('payment', 'Web\PaymentController');
    Route::get('/payment/edit/{id}', 'Web\PaymentController@edit')->name('payment.edit');

    // Product
    Route::resource('product', 'Web\ProductController');

    // Supplier
    Route::resource('supplier', 'Web\SupplierController');

    // Shipper
    Route::resource('shipper', 'Web\ShipperController');
    Route::get('/shipper/edit/{id}', 'Web\ShipperController@edit')->name('shipper.edit');

    // variant
    Route::resource('variant', 'Web\VariantController');
    Route::get('/variant/edit/{id}', 'Web\VariantController@edit')->name('variant.edit');

    // Variant Options
    Route::resource('voption', 'Web\VariantOptionController');
    Route::get('voption/create', 'Web\VariantOptionController@create')->name('voption.create');
    Route::get('/voption/edit/{id}', 'Web\VariantOptionController@edit')->name('voption.edit');

    //
});







Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/partials/admin/defaultjs.blade.php
<!--[if lt IE 9]>
<script src="../assets/global/plugins/respond.min.js"></script>
<script src="../assets/global/plugins/excanvas.min.js"></script> 
<script src="../assets/global/plugins/ie8.fix.min.js"></script> 
<![endif]-->
<!-- BEGIN CORE PLUGINS -->
<script src="{{asset('assets/global/plugins/jquery.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/global/plugins/bootstrap/js/bootstrap.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/global/plugins/js.cookie.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/global/plugins/jquery.blockui.min.js')}}" type="text/javascript"></script>
<script src="{{asset('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js')}}" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="{{asset('assets/global/scripts/app.min.js')}}" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN THEME LAYOUT SCRIPTS -->
<script src="{{asset('/assets/layouts/layout/scripts/layout.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/assets/layouts/layout/scripts/demo.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/assets/layouts/global/scripts/quick-sidebar.min.js')}}" type="text/javascript"></script>
<script src="{{asset('/assets/layouts/global/scripts/quick-nav.min.js')}}" type="text/javascript"></script>
<!-- END THEME LAYOUT SCRIPTS -->
<script src="{{asset('js/sweetalert2.min.js')}}"></script>
<script src="{{asset('js/toastr.min.js')}}"></script>
{!! Toastr::message() !!}

<script> 
    @if($errors->any())
        @foreach($errors->all() as $error)
        toastr.error('{{ $error }}', 'Error', {
                "closeButton": true,
                "progressBar": true
        });
        @endforeach
    @else
        toastr.options = {
        "closeButton": true,
        "debug": false,
        "newestOnTop": false,
        "progressBar": true,
        "positionClass": "toast-top-right"
        }
    @endif
</script>
@stack('js')

resources/views/partials/admin/footer.blade.php
<div class="page-footer-inner"> 2016 &copy; Metronic Theme By
    <a target="_blank" href="http://keenthemes.com">Keenthemes</a> &nbsp;|&nbsp;
    <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
</div>
<div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
</div>

resources/views/partials/admin/head.blade.php
<meta charset="utf-8" />
<title>@yield('title')</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1" name="viewport" />
<meta content="Preview page of Metronic Admin Theme #1 for blank page layout" name="description" />
<meta content="" name="author" />
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/simple-line-icons/simple-line-icons.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN THEME GLOBAL STYLES -->
<link href="{{asset('/assets/global/css/components.min.css')}}" rel="stylesheet" id="style_components" type="text/css" />
<link href="{{asset('/assets/global/css/plugins.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END THEME GLOBAL STYLES -->
<!-- BEGIN THEME LAYOUT STYLES -->
<link href="{{asset('/assets/layouts/layout/css/layout.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{asset('/assets/layouts/layout/css/themes/darkblue.min.css')}}" rel="stylesheet" type="text/css" id="style_color" />
<link href="{{asset('/assets/layouts/layout/css/custom.min.css')}}" rel="stylesheet" type="text/css" />
<!-- END THEME LAYOUT STYLES -->
<link rel="stylesheet" href="{{asset('css/toastr.min.css')}}">
<style>
    .page-content-white .page-content .page-bar {
        margin-bottom: 15px;
    }
</style>
<link rel="shortcut icon" href="{{asset('assets/favicon.ico')}}" />
@stack('css')

resources/views/partials/admin/header.blade.php
<div class="page-header-inner ">
    <!-- BEGIN LOGO -->
    <div class="page-logo">
        <a href="index.html">
            <img src="{{asset('img/admin/logo.png')}}" alt="logo" class="logo-default" /> </a>
        <div class="menu-toggler sidebar-toggler">
            <span></span>
        </div>
    </div>
    <!-- END LOGO -->
    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
        <span></span>
    </a>
    <!-- END RESPONSIVE MENU TOGGLER -->
    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
        <ul class="nav navbar-nav pull-right">
            <!-- BEGIN NOTIFICATION DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after "dropdown-extended" to change the dropdown styte -->
            <!-- DOC: Apply "dropdown-hoverable" class after below "dropdown" and remove data-toggle="dropdown" data-hover="dropdown" data-close-others="true" attributes to enable hover dropdown mode -->
            <!-- DOC: Remove "dropdown-hoverable" and add data-toggle="dropdown" data-hover="dropdown" data-close-others="true" attributes to the below A element with dropdown-toggle class -->
            <li class="dropdown dropdown-extended dropdown-notification" id="header_notification_bar">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <i class="icon-bell"></i>
                    <span class="badge badge-default"> 7 </span>
                </a>
                <ul class="dropdown-menu">
                    <li class="external">
                        <h3>
                            <span class="bold">12 pending</span> notifications</h3>
                        <a href="page_user_profile_1.html">view all</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 250px;" data-handle-color="#637283">
                            <li>
                                <a href="javascript:;">
                                    <span class="time">just now</span>
                                    <span class="details">
                                        <span class="label label-sm label-icon label-success">
                                            <i class="fa fa-plus"></i>
                                        </span> New user registered. </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- END NOTIFICATION DROPDOWN -->
            <!-- BEGIN INBOX DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <i class="icon-envelope-open"></i>
                    <span class="badge badge-default"> 4 </span>
                </a>
                <ul class="dropdown-menu">
                    <li class="external">
                        <h3>You have
                            <span class="bold">7 New</span> Messages</h3>
                        <a href="app_inbox.html">view all</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                            <li>
                                <a href="#">
                                    <span class="photo">
                                        <img src="{{asset('img/admin/profile/avatar3_small.jpg')}}" class="img-circle" alt=""> </span>
                                    <span class="subject">
                                        <span class="from"> Lisa Wong </span>
                                        <span class="time">Just Now </span>
                                    </span>
                                    <span class="message"> Vivamus sed auctor nibh congue nibh. auctor nibh auctor nibh... </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- END INBOX DROPDOWN -->
            <!-- BEGIN TODO DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <i class="icon-calendar"></i>
                    <span class="badge badge-default"> 3 </span>
                </a>
                <ul class="dropdown-menu extended tasks">
                    <li class="external">
                        <h3>You have
                            <span class="bold">12 pending</span> tasks</h3>
                        <a href="app_todo.html">view all</a>
                    </li>
                    <li>
                        <ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
                            <li>
                                <a href="javascript:;">
                                    <span class="task">
                                        <span class="desc">New release v1.2 </span>
                                        <span class="percent">30%</span>
                                    </span>
                                    <span class="progress">
                                        <span style="width: 40%;" class="progress-bar progress-bar-success" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100">
                                            <span class="sr-only">40% Complete</span>
                                        </span>
                                    </span>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </li>
            <!-- END TODO DROPDOWN -->
            <!-- BEGIN USER LOGIN DROPDOWN -->
            <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
            <li class="dropdown dropdown-user">
                <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                    <img alt="" class="img-circle" src="{{asset('img/admin/profile/avatar3_small.jpg')}}" />
                    <span class="username username-hide-on-mobile"> {{ Auth::user()->name }} </span>
                    <i class="fa fa-angle-down"></i>
                </a>
                <ul class="dropdown-menu dropdown-menu-default">
                    <li>
                        <a href="page_user_profile_1.html">
                            <i class="icon-user"></i> My Profile </a>
                    </li>
                    <li>
                        <a href="page_user_lock_1.html">
                            <i class="icon-lock"></i> Change Password </a>
                    </li>
                    <li class="divider"> </li> 
                    <li>
                        <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                            <i class="icon-key"></i> Log Out 
                        </a>
                        
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </li>
                </ul>
            </li>
            <!-- END USER LOGIN DROPDOWN -->
        </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->
</div>

resources/views/partials/admin/sidebar.blade.php
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
	<!-- BEGIN SIDEBAR -->
	<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
	<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
	<div class="page-sidebar navbar-collapse collapse">
		<!-- BEGIN SIDEBAR MENU -->
		<!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
		<!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
		<!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
		<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
		<!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
		<!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
		<ul class="page-sidebar-menu  page-header-fixed " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
			<!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
			<!-- BEGIN SIDEBAR TOGGLER BUTTON -->
			<li class="sidebar-toggler-wrapper hide">
				<div class="sidebar-toggler">
					<span></span>
				</div>
			</li>
			<!-- END SIDEBAR TOGGLER BUTTON -->
			<!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
			<li class="sidebar-search-wrapper">
				<!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
				<!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
				<!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
				<form class="sidebar-search  sidebar-search-bordered" action="page_general_search_3.html" method="POST">
					<a href="javascript:;" class="remove">
						<i class="icon-close"></i>
					</a>
					<div class="input-group">
						<input type="text" class="form-control" placeholder="Search...">
						<span class="input-group-btn">
							<a href="javascript:;" class="btn submit">
								<i class="icon-magnifier"></i>
							</a>
						</span>
					</div>
				</form>
				<!-- END RESPONSIVE QUICK SEARCH FORM -->
			</li>
			<li class="nav-item start {{ Request::is('/home') ? 'active' : ''}}">
				<a href="{{url('/home')}}" class="nav-link nav-toggle">
					<i class="icon-home"></i>
					<span class="title">Dashboard</span>                               
				</a>
			</li>
			
			<li class="nav-item start {{ Request::is('admin/category*') ? 'active' : ''}}">
				<a href="{{route('admin.category.index')}}" class="nav-link nav-toggle">
					<i class="icon-list"></i>
					<span class="title">Categories</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/customer*') ? 'active' : ''}}">
				<a href="{{route('admin.customer.index')}}" class="nav-link nav-toggle">
					<i class="icon-users"></i>
					<span class="title">Customers</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/payment*') ? 'active' : ''}}">
				<a href="{{route('admin.payment.index')}}" class="nav-link nav-toggle">
					<i class="icon-wallet"></i>
					<span class="title">Payments</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/product*') ? 'active' : ''}}">
				<a href="{{route('admin.product.index')}}" class="nav-link nav-toggle">
					<i class="icon-present"></i>
					<span class="title">Products</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/supplier*') ? 'active' : ''}}">
				<a href="{{route('admin.supplier.index')}}" class="nav-link nav-toggle">
					<i class="icon-layers"></i>
					<span class="title">Suppliers</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/shipper*') ? 'active' : ''}}">
				<a href="{{route('admin.shipper.index')}}" class="nav-link nav-toggle">
					<i class="icon-bag"></i>
					<span class="title">Shippers</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/variant*') ? 'active' : ''}}">
				<a href="{{route('admin.variant.index')}}" class="nav-link nav-toggle">
					<i class="icon-tag"></i>
					<span class="title">Variants</span>                               
				</a>
			</li>

			<li class="nav-item start {{ Request::is('admin/voption*') ? 'active' : ''}}">
				<a href="{{route('admin.voption.index')}}" class="nav-link nav-toggle">
					<i class="icon-support"></i>
					<span class="title">Variant Options</span>                               
				</a>
			</li>

			<li class="heading">
				<h3 class="uppercase">Features</h3>
			</li>
			
			<li class="nav-item start ">
				<a href="javascript:;" class="nav-link nav-toggle">
					<i class="icon-social-dribbble"></i>
					<span class="title">General</span>
					<span class="arrow"></span>
				</a>
				<ul class="sub-menu">
					<li class="nav-item  ">
						<a href="page_general_about.html" class="nav-link ">
							<i class="icon-info"></i>
							<span class="title">About</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_contact.html" class="nav-link ">
							<i class="icon-call-end"></i>
							<span class="title">Contact</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="javascript:;" class="nav-link nav-toggle">
							<i class="icon-notebook"></i>
							<span class="title">Portfolio</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub-menu">
							<li class="nav-item ">
								<a href="page_general_portfolio_1.html" class="nav-link "> Portfolio 1 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_portfolio_2.html" class="nav-link "> Portfolio 2 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_portfolio_3.html" class="nav-link "> Portfolio 3 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_portfolio_4.html" class="nav-link "> Portfolio 4 </a>
							</li>
						</ul>
					</li>
					<li class="nav-item  ">
						<a href="javascript:;" class="nav-link nav-toggle">
							<i class="icon-magnifier"></i>
							<span class="title">Search</span>
							<span class="arrow"></span>
						</a>
						<ul class="sub-menu">
							<li class="nav-item ">
								<a href="page_general_search.html" class="nav-link "> Search 1 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_search_2.html" class="nav-link "> Search 2 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_search_3.html" class="nav-link "> Search 3 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_search_4.html" class="nav-link "> Search 4 </a>
							</li>
							<li class="nav-item ">
								<a href="page_general_search_5.html" class="nav-link "> Search 5 </a>
							</li>
						</ul>
					</li>
					<li class="nav-item  ">
						<a href="page_general_pricing.html" class="nav-link ">
							<i class="icon-tag"></i>
							<span class="title">Pricing</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_faq.html" class="nav-link ">
							<i class="icon-wrench"></i>
							<span class="title">FAQ</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_blog.html" class="nav-link ">
							<i class="icon-pencil"></i>
							<span class="title">Blog</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_blog_post.html" class="nav-link ">
							<i class="icon-note"></i>
							<span class="title">Blog Post</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_invoice.html" class="nav-link ">
							<i class="icon-envelope"></i>
							<span class="title">Invoice</span>
						</a>
					</li>
					<li class="nav-item  ">
						<a href="page_general_invoice_2.html" class="nav-link ">
							<i class="icon-envelope"></i>
							<span class="title">Invoice 2</span>
						</a>
					</li>
				</ul>
			</li>
		</ul>
		<!-- END SIDEBAR MENU -->
		<!-- END SIDEBAR MENU -->
	</div>
	<!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->